"""The bridge between the policy's world (radians, MuJoCo joint order) and the
servos' world (encoder counts, bus ids), built from the on-robot calibration.

Two things here are load-bearing for safety.

**Ordering.** The policy's observation slices ``qpos[7:]`` and its action
indexes actuators, both in the model's joint order. The calibration file is
keyed by name in *its own* order (the order a human walks the robot). Those
are different orders, and getting them confused sends every command to the
wrong motor. So nothing is positional here: the mapping is built by matching
names, every policy joint must resolve to exactly one calibrated joint, and
any mismatch is a hard failure at construction.

**The encoder seam.** An STS3215 reports 0..4095 and wraps. Reading across the
wrap is handled by taking the shortest signed difference from the zero. But
*commanding* across it is not recoverable: if a joint's zero sits near count 0,
a small negative target wraps to ~4090 and the servo takes the long way
around -- almost a full revolution, at speed, through whatever the leg is
attached to. ``seam_violations()`` refuses to arm when any joint's reachable
command window crosses the wrap, because there is no safe way to issue that
command.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

TWO_PI = 2.0 * np.pi

#: How far a joint's measured travel may miss the policy's nominal pose before
#: it is treated as a genuine zero disagreement. A sweep endpoint landing a
#: fraction of a degree short is measurement noise -- the calibration's own
#: reach tolerance is 1 deg and one encoder count is 0.088 deg. A flipped
#: direction or a zero taken in the wrong pose is tens of degrees.
NOMINAL_TOLERANCE_RAD = np.radians(3.0)


class JointMapError(Exception):
    """Raised when the policy and the calibration cannot be reconciled."""


@dataclass(frozen=True)
class SeamViolation:
    name: str
    zero_raw: int
    lo_counts: float
    hi_counts: float
    counts_per_rev: int
    scope: str = "command"      # "command" or "travel"

    def describe(self) -> str:
        what = ("command window" if self.scope == "command"
                else "full travel range")
        certainty = ("the policy will drive it across the wrap"
                     if self.scope == "command"
                     else "the ramp crosses the wrap if the robot is armed "
                          "from that part of its travel")
        return (
            f"{self.name}: zero at count {self.zero_raw}, {what} spans "
            f"[{self.lo_counts:.0f}, {self.hi_counts:.0f}] which crosses the "
            f"0/{self.counts_per_rev - 1} wrap -- {certainty}"
        )


def _normalize_name(name: str) -> str:
    """Strip conventional suffixes so MuJoCo and calibration names can meet."""
    lowered = name.lower()
    for suffix in ("_joint", "_jnt"):
        if lowered.endswith(suffix):
            return lowered[: -len(suffix)]
    return lowered


def resolve_joint_names(policy_names, calibration_names, aliases=None):
    """Match each policy joint to exactly one calibrated joint.

    MuJoCo models generated by onshape-to-robot suffix every joint with
    ``_joint``; a human-written calibration file usually does not. Rather than
    force one convention (which would invalidate an existing calibration), this
    matches exactly first, then on the suffix-stripped name, and finally on an
    explicit alias table.

    The result must be a bijection. Anything ambiguous, unmatched or left over
    is an error -- a partial match here would put a command on the wrong motor,
    which is the failure this whole module exists to prevent.

    Returns ``(mapping, notes)`` where mapping is policy name -> calibration key
    and notes describes any non-identity match, for logging.
    """
    aliases = dict(aliases or {})
    available = list(calibration_names)

    by_exact = {name: name for name in available}
    by_normal: dict[str, list[str]] = {}
    for name in available:
        by_normal.setdefault(_normalize_name(name), []).append(name)

    mapping: dict[str, str] = {}
    notes: list[str] = []
    problems: list[str] = []

    for name in policy_names:
        if name in aliases:
            target = aliases[name]
            if target not in by_exact:
                problems.append(f"alias {name!r} -> {target!r} names no calibrated joint")
                continue
            mapping[name] = target
            notes.append(f"{name} -> {target} (alias)")
            continue
        if name in by_exact:
            mapping[name] = name
            continue
        candidates = by_normal.get(_normalize_name(name), [])
        if len(candidates) == 1:
            mapping[name] = candidates[0]
            notes.append(f"{name} -> {candidates[0]}")
        elif len(candidates) > 1:
            problems.append(
                f"{name!r} matches several calibrated joints {candidates}; "
                "add an explicit alias"
            )
        else:
            problems.append(f"{name!r} has no calibrated joint")

    used = list(mapping.values())
    duplicated = {n for n in used if used.count(n) > 1}
    if duplicated:
        problems.append(f"these calibrated joints were matched more than once: "
                        f"{sorted(duplicated)}")
    unused = [n for n in available if n not in used]
    if unused:
        problems.append(
            f"these calibrated joints are not driven by the model: {unused}"
        )

    if problems:
        raise JointMapError(
            "cannot reconcile the model's joints with the calibration:\n  "
            + "\n  ".join(problems)
            + f"\n\n  model       : {list(policy_names)}"
            + f"\n  calibration : {available}"
        )
    return mapping, notes


class JointMap:
    """Vectorised conversions between policy radians and servo counts."""

    def __init__(self, joint_names, calibrations, xml_lower, xml_upper,
                 action_scale, limit_margin_rad=0.0, default_pose=None,
                 aliases=None, nominal_tolerance_rad=NOMINAL_TOLERANCE_RAD):
        """
        :param joint_names: policy joint names, in MuJoCo order.
        :param calibrations: ``{name: JointCalibration}`` from the calibration store.
        :param xml_lower/upper: per-joint limits the policy was trained against.
        :param action_scale: the env's action scale, in radians.
        :param limit_margin_rad: shrink the safe envelope by this much per side,
            except where that would exclude the nominal pose (see below).
        :param default_pose: the policy's target pose, 0 rad per joint for this
            env. Defaults to zeros.
        :param nominal_tolerance_rad: how far the measured range may miss the
            nominal pose before that counts as a real zero disagreement rather
            than sweep imprecision.
        """
        self.names = list(joint_names)
        n = len(self.names)

        # Name resolution, then a strict bijection check. The model's joint
        # ORDER need not match the calibration file's order -- and on this robot
        # it does not, the left leg is enumerated the other way round -- so
        # nothing below is positional.
        self.name_map, self.name_notes = resolve_joint_names(
            self.names, list(calibrations), aliases
        )

        self.servo_ids = np.empty(n, dtype=np.int32)
        self.zero_raw = np.empty(n, dtype=np.float64)
        self.direction = np.empty(n, dtype=np.float64)
        self.counts_per_rev = np.empty(n, dtype=np.float64)
        calib_lower = np.empty(n, dtype=np.float64)
        calib_upper = np.empty(n, dtype=np.float64)

        seen_ids: dict[int, str] = {}
        for index, name in enumerate(self.names):
            cal = calibrations[self.name_map[name]]
            if cal.servo_id in seen_ids:
                raise JointMapError(
                    f"servo id {cal.servo_id} is claimed by both "
                    f"'{seen_ids[cal.servo_id]}' and '{name}'"
                )
            seen_ids[cal.servo_id] = name
            self.servo_ids[index] = cal.servo_id
            self.zero_raw[index] = cal.zero_raw
            self.direction[index] = cal.direction
            self.counts_per_rev[index] = cal.counts_per_rev
            calib_lower[index] = np.radians(cal.min_deg)
            calib_upper[index] = np.radians(cal.max_deg)

        self.xml_lower = np.asarray(xml_lower, dtype=np.float64)
        self.xml_upper = np.asarray(xml_upper, dtype=np.float64)
        self.calib_lower = calib_lower
        self.calib_upper = calib_upper
        self.action_scale = float(action_scale)

        self.default_pose = (np.zeros(n) if default_pose is None
                             else np.asarray(default_pose, dtype=np.float64))

        # The envelope is the intersection of what the model was trained inside
        # and what this physical robot was measured to reach. Taking the tighter
        # of the two on each side can only ever reduce travel, never invent it.
        hard_lower = np.maximum(calib_lower, self.xml_lower)
        hard_upper = np.minimum(calib_upper, self.xml_upper)

        # A joint may end up a hair "outside" its own measured range, because the
        # two numbers come from different measurements of different quality. The
        # zero is set deliberately: the operator aligns the link vertically and
        # presses a key. The min/max are captured by sweeping to a target and
        # auto-recording within a degree. So when a sweep endpoint lands a
        # fraction of a degree the wrong side of the zero, it is the sweep that
        # is imprecise, not the zero -- and refusing to run over two encoder
        # counts would be absurd. Absorb that, and record it for the log.
        #
        # A real zero disagreement -- a flipped direction, a zero taken in the
        # wrong pose -- is tens of degrees, and stays fatal.
        gap_low = hard_lower - self.default_pose
        gap_high = self.default_pose - hard_upper
        worst = np.maximum(gap_low, gap_high)

        fatal = np.nonzero(worst > nominal_tolerance_rad)[0]
        if fatal.size:
            details = ", ".join(
                f"{self.names[i]} (nominal {np.degrees(self.default_pose[i]):+.1f} deg "
                f"vs [{np.degrees(hard_lower[i]):+.1f}, "
                f"{np.degrees(hard_upper[i]):+.1f}], off by "
                f"{np.degrees(worst[i]):.1f} deg)"
                for i in fatal
            )
            raise JointMapError(
                "the policy's nominal pose lies outside the allowed range for: "
                f"{details}.\nThe calibration and the trained model disagree "
                "about where this joint's zero is. Re-check the joint's "
                "`direction` in joint_limits.yaml and recalibrate it:\n"
                "  ros2 run humanoid_calibration calibrate --only <joint> --force"
            )

        #: Joints whose measured range missed the nominal pose by less than the
        #: tolerance, and were widened to include it. Informational.
        snapped = np.nonzero((worst > 1e-9) & (worst <= nominal_tolerance_rad))[0]
        self.snapped = [
            (self.names[i], float(np.degrees(worst[i]))) for i in snapped
        ]
        hard_lower = np.minimum(hard_lower, self.default_pose)
        hard_upper = np.maximum(hard_upper, self.default_pose)

        # The margin must never exclude the nominal pose. A joint whose standing
        # position is legitimately *at* an endpoint -- a knee that cannot
        # hyper-extend has its straight pose at the limit -- would otherwise end
        # up with an envelope the robot can never be inside, and it could never
        # arm.
        self.safe_lower = np.minimum(hard_lower + limit_margin_rad, self.default_pose)
        self.safe_upper = np.maximum(hard_upper - limit_margin_rad, self.default_pose)
        #: Joints where the nominal pose sits on (or within the margin of) a
        #: hard limit, so the margin buys no protection on that side.
        #: Informational, not an error -- but worth logging, because those
        #: joints have zero cushion between the standing pose and a hard stop.
        pinched_low = hard_lower + limit_margin_rad > self.default_pose + 1e-9
        pinched_high = hard_upper - limit_margin_rad < self.default_pose - 1e-9
        self.unmargined = [
            self.names[i] for i in np.nonzero(pinched_low | pinched_high)[0]
        ]

        inverted = np.nonzero(self.safe_lower >= self.safe_upper)[0]
        if inverted.size:
            details = ", ".join(
                f"{self.names[i]} ([{np.degrees(self.safe_lower[i]):+.1f}, "
                f"{np.degrees(self.safe_upper[i]):+.1f}] deg)"
                for i in inverted
            )
            raise JointMapError(
                "these joints have an empty safe range after intersecting the "
                f"calibration with the model limits: {details}"
            )

    @property
    def size(self) -> int:
        return len(self.names)

    # -- conversions -------------------------------------------------------

    def counts_to_rad(self, counts) -> np.ndarray:
        """Encoder counts -> joint radians, taking the shortest way round."""
        counts = np.asarray(counts, dtype=np.float64)
        delta = np.mod(counts - self.zero_raw, self.counts_per_rev)
        half = self.counts_per_rev / 2.0
        delta = np.where(delta > half, delta - self.counts_per_rev, delta)
        return self.direction * delta * TWO_PI / self.counts_per_rev

    def rad_to_counts_unwrapped(self, radians) -> np.ndarray:
        """Joint radians -> counts *without* the modulo, for seam analysis."""
        radians = np.asarray(radians, dtype=np.float64)
        return self.zero_raw + self.direction * radians * self.counts_per_rev / TWO_PI

    def rad_to_counts(self, radians) -> np.ndarray:
        """Joint radians -> the integer count to command."""
        raw = self.rad_to_counts_unwrapped(radians)
        return np.mod(np.rint(raw), self.counts_per_rev).astype(np.int32)

    # -- envelope ----------------------------------------------------------

    def clamp(self, radians) -> np.ndarray:
        """Clamp targets into the safe envelope. The last line of defence."""
        return np.clip(np.asarray(radians, dtype=np.float64),
                       self.safe_lower, self.safe_upper)

    def command_window(self) -> tuple[np.ndarray, np.ndarray]:
        """Widest targets the policy can produce, after clamping.

        The env computes ``clip(0 + action*action_scale, limits)`` with the
        action bounded to [-1, 1] by tanh, so the reachable set is at most
        +/- action_scale, further reduced by the safe envelope.
        """
        lo = np.maximum(-self.action_scale, self.safe_lower)
        hi = np.minimum(self.action_scale, self.safe_upper)
        return lo, hi

    def seam_violations(self, margin_counts: float = 16.0) -> list[SeamViolation]:
        """Joints that would have to be driven across the 0/cpr wrap.

        Two scopes, both fatal:

        ``command`` -- the window the policy can reach, ``+/-action_scale``
        intersected with the safe envelope. A crossing here is certain to
        happen the moment the policy runs.

        ``travel`` -- the joint's whole safe range. Arming does not start from
        the standing pose, it starts from wherever the robot physically is, and
        the ramp then walks from there to the policy's target. So a joint whose
        *travel* crosses the wrap is unsafe even when its command window does
        not: it just needs to be armed from the far side.
        """
        violations = []
        for scope, (lo_rad, hi_rad) in (
            ("command", self.command_window()),
            ("travel", (self.safe_lower, self.safe_upper)),
        ):
            lo_counts = self.rad_to_counts_unwrapped(lo_rad)
            hi_counts = self.rad_to_counts_unwrapped(hi_rad)
            low = np.minimum(lo_counts, hi_counts) - margin_counts
            high = np.maximum(lo_counts, hi_counts) + margin_counts
            for index in range(self.size):
                if low[index] < 0.0 or high[index] > self.counts_per_rev[index] - 1.0:
                    if any(v.name == self.names[index] for v in violations):
                        continue        # already reported at the tighter scope
                    violations.append(
                        SeamViolation(
                            name=self.names[index],
                            zero_raw=int(self.zero_raw[index]),
                            lo_counts=float(low[index]),
                            hi_counts=float(high[index]),
                            counts_per_rev=int(self.counts_per_rev[index]),
                            scope=scope,
                        )
                    )
        return violations

    def describe(self) -> str:
        lo, hi = self.command_window()
        lines = []
        if self.name_notes:
            lines.append("name resolution (model -> calibration):")
            lines += [f"  {note}" for note in self.name_notes]
        lines.append(
            f"{'joint (model order)':<24}{'id':>4}{'zero':>7}{'safe range (deg)':>22}"
            f"{'command window (deg)':>24}"
        )
        for index, name in enumerate(self.names):
            lines.append(
                f"{name:<24}{self.servo_ids[index]:>4}{int(self.zero_raw[index]):>7}"
                f"{np.degrees(self.safe_lower[index]):>11.1f} .."
                f"{np.degrees(self.safe_upper[index]):>8.1f}"
                f"{np.degrees(lo[index]):>13.1f} ..{np.degrees(hi[index]):>8.1f}"
            )
        return "\n".join(lines)
